# Generated by Django 5.2.5 on 2025-09-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount in smallest currency unit, e.g., paise')),
                ('currency', models.CharField(default='inr', max_length=10)),
                ('status', models.CharField(default='created', max_length=20)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=128, null=True)),
                ('stripe_checkout_session', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
