# Generated by Django 5.2.5 on 2025-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promotions',
            field=models.BooleanField(default=True),
        ),
    ]
