# Generated by Django 5.2.5 on 2025-09-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='s_vendor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
