# Generated by Django 5.2.5 on 2025-09-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_s_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True, default=False),
        ),
    ]
