# Generated by Django 5.2.5 on 2025-09-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_pincode_address_state_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
