# Generated by Django 5.2.5 on 2025-09-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address_customer_email_address_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, default='home', max_length=12, null=True),
        ),
    ]
