# Generated by Django 5.2.5 on 2025-09-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razor_pay_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
