# Generated by Django 5.2.5 on 2025-09-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_pincode_address_state_alter_address_user'),
        ('orders', '0005_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Created', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
    ]
