# Generated by Django 5.2.5 on 2025-09-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_status_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Paid', 'Paid'), ('Failed', 'Failed')], max_length=32),
        ),
    ]
