# Generated by Django 5.2.5 on 2025-09-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_discount_percent_product_mrp_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_250g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_250g',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
