# Generated by Django 5.2.5 on 2025-09-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_cartitem_added_at_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
