# Generated by Django 5.2.5 on 2025-09-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_main_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_category',
        ),
    ]
